# Generated by Django 3.0.2 on 2020-01-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200122_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='juser',
            name='last_name',
        ),
    ]
