# Generated by Django 3.0.2 on 2020-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20200117_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='domain',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationverification',
            name='domain',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationverification',
            name='verification_hash',
            field=models.CharField(max_length=258),
        ),
    ]
