# Generated by Django 3.0.2 on 2020-01-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20200123_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='domain',
            new_name='domain_name',
        ),
        migrations.RenameField(
            model_name='integrationverification',
            old_name='domain',
            new_name='domain_name',
        ),
    ]
