# Generated by Django 3.0.2 on 2020-01-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20200123_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integration',
            name='verification_hash',
            field=models.CharField(default=2345, max_length=258),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IntegrationVerification',
        ),
    ]
